name: exmapl1_wf

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                 sparse-checkout: .
            - name: List and read file
              run: | 
                 echo "My first action"
                 ls -ltra
                 cat README.md
            
            - name: Generate ASCII artwork
              run: cowsay -f dragon "Run for cover, I am a dragon..." >> dragon.txt

        


