name: exmapl1_wf

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                 sparse-checkout: .
            - name: Welcome Message
              run: echo "My first action"

            - name: List Files
              run: ls

            - name: Read file
              run:  cat README.md


