name: Generate Ascii Artwork

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Shell Script
          run: cowsay -f dragon "Run for cover. Dragon about" >> dragon.txt

        - name: Slee for 30 seconds
          run: sleep 30

    test_job_2:
        runs-on: ubuntu-latest
        steps:
        - name: Slee for 10 seconds
          run: sleep 10

        - name: Test file Exists
          run: grep -i "dragon.txt"

    deploy_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Read File
          run: cat dragon.txt

        - name: Deploy
          run: echo Deploying...
            
          
